export const APP_CONFIG = {
  appName: 'FaithLink Command Center',
  version: 'Phase 13B Firebase Auth Local Data',
  dataMode: 'localStorage',
  deploymentPhase: 'auth-enabled-local-data',
  firebaseEnabled: true,
  firebaseConnected: true,
  authEnabled: true,
  authConnected: true,
  authRequired: true,
  firestoreConnected: false,
  hostingStatus: 'Firebase Hosting Ready/Active',
  pwaPrep: true,
  installableStatus: 'Manifest Prepared',
  offlineStatus: 'Service Worker Not Connected',
  mobileStatus: 'Responsive Local App',
  dataSyncStatus: 'Not Connected',
  syncStatus: 'Not Connected',
}
