export const APP_CONFIG = {
  appName: 'FaithLink Command Center',
  version: 'FaithLink Command Center v1.0',
  dataMode: 'firestore',
  deploymentPhase: 'cloud-sync-release',
  firebaseEnabled: true,
  firebaseConnected: true,
  authEnabled: true,
  authConnected: true,
  authRequired: true,
  firestoreConnected: true,
  hostingStatus: 'Firebase Hosting Active',
  pwaPrep: true,
  installableStatus: 'Manifest Prepared',
  offlineStatus: 'Service Worker Not Connected',
  mobileStatus: 'Responsive Local App',
  dataSyncStatus: 'Cloud Sync Enabled',
  syncStatus: 'Cloud Sync Enabled',
  releaseStatus: 'v1.0 Candidate',
}
