export const APP_CONFIG = {
  appName: 'FaithLink Command Center',
  version: 'Phase 12 Mobile PWA Prep Local',
  dataMode: 'localStorage',
  deploymentPhase: 'prep',
  firebaseEnabled: false,
  firebaseConnected: false,
  authEnabled: false,
  authConnected: false,
  firestoreConnected: false,
  hostingStatus: 'Local Only',
  pwaPrep: true,
  installableStatus: 'Manifest Prepared',
  offlineStatus: 'Service Worker Not Connected',
  mobileStatus: 'Responsive Local App',
  dataSyncStatus: 'Not Connected',
}
